import oil1 from "../assets/caro2a.jpg";

const data={
    productItems:[
        {
            id:1,
            name:'cocunut',
            liter:1/2,
            price:200,
            image:oil1,
        },
        {
            id:2,
            name:'gengelly',
            liter:1,
            price:250,
            image:oil1,
        },
        {
            id:3,
            name:'castrol',
            liter:1.5,
            price:150,
            image:oil1,
        },
        {
            id:4,
            name:'castrol',
            liter:1,
            price:150,
            image:oil1,
        },
        {
            id:5,
            name:'castrol',
            liter:1,
            price:150,
            image:oil1,
        },
        {
            id:6,
            name:'castrol',
            liter:1,
            price:150,
            image:oil1,
        },
        {
            id:7,
            name:'castrol',
            liter:1,
            price:150,
            image:oil1,
        },
        {
            id:8,
            name:'castrol',
            liter:1,
            price:100,
            image:oil1,
        }
    ]
}
export default data;